import type { Metadata } from "next";
import { Almarai, } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const almaria = Almarai({
subsets:['arabic'],
weight:['400','700','800']
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${almaria.className} container p-5 m-auto`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
